/*Los siguientes queries son los necesarios para poder replicar todas las beses de datos de consulta de LAATS, para que este
proceso funcione correctamente es necesario correr lo queries en el orden que aparecen, para tener una mejor comprension ver el 
diagrama de las bases de datos adjunta en esta carpeta.*/

CREATE TABLE reporte_actividades_diarias (
    supervisor_turno_a: varchar(35),
    supervisor_turno_b: varchar(35),
    supervisor_turno_c: varchar(35),
    inasistencias: varchar(100),
    permisos: varchar(100),
    altas_nuevos_ingresos: varchar(100),
    bajas_renuncias_despidos: varchar(100),
    sups_IGSS: varchar(100),
    vacaciones: varchar(100),
    plaza_vacante: varchar(100),
    amonestados_con_dias_suspension: varchar(100),
    amonestados_sin_dias_suspension: varchar(100),
    personal_apoyo: varchar(100),
    total_reportes_personal: int,
    incidente_situacion: int,
    incidente_situacion_d: varchar(146),
    accidente: int,
    accidente_d: varchar(146),
    reclamo_equipaje_entrando: int,
    reclamo_equipaje_entrando_d: varchar(146),
    reclamo_equipaje_saliendo: int,
    reclamo_equipaje_saliendo_d: varchar(146),
    reclamo_carga: int,
    reclamo_carga_d: varchar(146),
    discrepancias_externas: int,
    discrepancias_externas_d: varchar(146),
    golpes_danos_unidades_interno: int,
    golpes_danos_unidades_interno_d: varchar(146),
    golpes_danos_unidades_externo: int,
    golpes_danos_unidades_externo_d: varchar(146),
    otros_reclamos: int,
    otros_reclamos_d: varchar(146)
    no_at_GSE: varchar(15),
    tipo_unidad_GSE: varchar(15),
    supervisor_GSE: varchar(15),
    tecnico: varchar(36),
    reporte_GSE: varchar(36),
    descripcion_falla_GSE: varchar(146),
    no_at_alquilado: varchar(16),
    tipo_unidad_alquilado: varchar(31),
    hora_inicio_alquilado: TIME,
    hora_final_alquilado: TIME,
    supervisor_alquilado: varchar(36),
    alquiler_alquilado: varchar(51),
    razon_por_la_cual_se_alquila_GSE: varchar(145),
    terminado: BIT default 'false'
);

CREATE TABLE SLA2 (
    no_correlativo int,
    cantidad_pxs_outbound int,
    vuelo_con_equipaje_priority_pxs BIT default 'false',
    cantidad_equipaje_priority_local_red_pxs int,
    cantidad_equipaje_priority_fisica_rampa_pxs int,
    observaciones_equipaje_priority_pxs varchar(250),
    demora_puntualidad_responsabilidad_laats_pxs BIT default 'false',
    codigos_demoras_puntualidad_laats_pxs varchar(15),
    cantidad_demoras_puntialidad_laats_pxs int,
    minutos_total_demora_pxs int,
    observaciones_demora_puntualidad_laats_pxs varchar(250),
    codigo_mbr_responsabilidad_laats_pxs BIT default 'false',
    codigos_mbr_pxs	varchar(15),
    cantidad_codigos_mbr_pxs int,
    observaciones_mbr_pxs varchar(250),
    demora_puntualidad_responsabilidad_laats_sap BIT default 'false',
    codigos_demoras_puntualidad_laats_sap varchar(15),
    cantidad_demoras_puntialidad_laats_sap int,
    minutos_total_demora_sap int,
    observaciones_demora_puntualidad_laats_sap varchar(250),
    codigo_mbr_responsabilidad_laats_sap BIT default 'false',
    codigos_mbr_sap	varchar(15),
    cantidad_codigos_mbr_sap int,
    observaciones_mbr_sap varchar(250),
    self_audit BIT default 'false',
    caso_documentacion BIT default 'false',
    cantidad_casos_documentacion int,
    observaciones_casos_documentacion varchar(250),
    peso_balance BIT default 'false',
    cantidad_saqueo_equipaje int,
    cantidad_dano_equipaje int,
    cargado_equipaje_prioritario_correctamente BIT default 'false',
    self_audit_sap BIT default 'false',
    diferencia_equipajes_priority_RED_y_Fisicas int,
    vuelo_fue_cargado_correctamente BIT default 'false',
    cantidad_demora_equipaje int,
    ubicacion_equipaje_priority_local_red_pxs int,
    ubicacion_equipaje_fisicas_rampa_pxs int,
    coinciden_cantidad_equipaje_red_fisica BIT default 'false',
    diferencia_red_fisicas_esta_misma BIT default 'false',
    FOREIGN KEY (no_correlativo) REFERENCES itinerarios(no_correlativo)
);

CREATE TABLE resultados_sla (
    no_correlativo int,
    otp_pxs	demoras_equipaje_pxs varchar(5),
    danos_equipaje_pxs int,
    cargado_equipaje_prioritario_pxs int,
    saqueo_equipaje_pxs	otp_sap int,
    cumplimiento_capacitacion_sap int,
    demoras_equipaje_sap int,
    otp_pxs_mensual int,
    cumplimiento_capacitacion_pxs_mensual int,
    demoras_equipaje_pxs_mensual int,
    danos_equipaje_pxs_mensual int,
    cargado_equipaje_prioritario_pxs_mensual int,
    saqueo_equipaje_pxs_mensual	otp_sap_mensual int,
    cumplimiento_capacitacion_sap_mensual	 int,
    demoras_equipaje_sap_mensual int,
    FOREIGN KEY (no_correlativo) REFERENCES itinerarios(no_correlativo)
);

CREATE TABLE codigos_sla (
    id_codigo int not null IDENTITY(1, 1),
    codigo varchar(6),
    id_operador int,
    departamento varchar(3),
    descripcion varchar(250),
    tipo_codigo	varchar(30),
    origen varchar(3)
);